module ARCRun

open Domain

let requiredProfileProperties = [
    ProfileRow.create("@id",                    Required, ONE,              [   (Schema.Text, OR)
                                                                                (Schema.URL, END)
                                                                            ], 
                                                                            "Used to distinguish the resource being described in JSON-LD.", 
                                                                            "**THIS PROFILE**")
    ProfileRow.create("@type",                  Required, ONE,              [   (Schema.Dataset, END)], 
                                                                            "Schema.org/Bioschemas class(es) for the resource declared using JSON-LD syntax.", 
                                                                            "**THIS PROFILE**")
    ProfileRow.create("additionalType",         Required, ONE,              [   (Schema.Text, OR)
                                                                                (Schema.URL, END)
                                                                            ], 
                                                                            "MUST be 'ARC Run' or ontology term to identify it as an ARC Run", 
                                                                            "**THIS PROFILE**")
    ProfileRow.create("identifier",             Required, ONE,              [   (Schema.Text, OR)
                                                                                (Schema.URL, END)
                                                                            ], 
                                                                            "A mandatory unique identifier, either a temporary identifier supplied by users or one generated by a repository or other database. For example, it could be an identifier complying with the LSID specification", 
                                                                            "**THIS PROFILE**")
]

let recommendedProfileProperties = [
    ProfileRow.create("name",                   Recommended, ONE,           [   (Schema.Text, END)],
                                                                            "A concise phrase used to encapsulate the purpose and goal of the ARC Run.",
                                                                            "**THIS PROFILE**")
    ProfileRow.create("description",            Recommended, ONE,           [   (Schema.Text, END)],
                                                                            "A textual description of the ARC Run, with components such as objective or goals.",
                                                                            "**THIS PROFILE**")
    ProfileRow.create("about",                  Recommended, MANY,          [ (MultiTypes.WorkflowInvocation, END)],
                                                                            "The Workflow Invocation(s) described by the ARC Run. MUST follow the [Workflow Invocation profile](#workflow-invocation). MUST be equal to the `mentions` property",
                                                                            "**THIS PROFILE**")
    ProfileRow.create("mentions",               Recommended, MANY,          [ (MultiTypes.WorkflowInvocation, END)],
                                                                            "The Workflow Invocation(s) described by the ARC Run. MUST follow the [Workflow Invocation profile](#workflow-invocation). MUST be equal to the `about` property",
                                                                            "**THIS PROFILE**")
    ProfileRow.create("creator",                Recommended, MANY,          [   (Schema.Person, END)],
                                                                            "The performer(s) of the ARC Run.",
                                                                            "**THIS PROFILE**")
    ProfileRow.create("hasPart",                Recommended, MANY,          [   (Schema.MediaObject, OR)
                                                                                (MultiTypes.WorkflowProtocol, END)
                                                                            ],
                                                                            "All data files that are part of the ARC Run. In an ARC, this should include all contents of the respective `run folder` represented by the ARC Run object.",
                                                                            "**THIS PROFILE**")
    ProfileRow.create("measurementMethod",      Recommended, ONE,           [   (Schema.URL, OR)
                                                                                (Schema.DefinedTerm, END)
                                                                            ],
                                                                            "Term to identify the technology used to perform the computation, e.g. statistical testing. The term can be free text or from, for example, a controlled vocabulary or an ontology.",
                                                                            "**THIS PROFILE**")
    ProfileRow.create("measurementTechnique",   Recommended, ONE,           [   (Schema.URL, OR)
                                                                                (Schema.DefinedTerm, END)
                                                                            ],
                                                                            "Software Publisher/Creator and/or Software name used for the computation.",
                                                                            "**THIS PROFILE**")
    // necessary according to https://www.researchobject.org/workflow-run-crate/profiles/process_run_crate
    // to be a valid process run crate root entity (when scoped profiles are eventually drafted for ro crate spec)
    ProfileRow.create("conformsTo",             Recommended, ONE,           [   (Schema.CreativeWork, END)], 
                                                                            """MUST reference a CreativeWork entity with an @id URI that is consistent with the versioned Permalink of this document, e.g. {"@id": "https://w3id.org/ro/wfrun/process/0.4"}""", 
                                                                            "https://www.researchobject.org/workflow-run-crate/profiles/process_run_crate")
]
let optionalProfileProperties = [
    ProfileRow.create("url",                    Optional, ONE,              [   (Schema.URL, END)],
                                                                            "The filename or path of the metadata file describing the run. Optional, since in some contexts like an ARC the filename is implicit.",
                                                                            "**THIS PROFILE**")
    ProfileRow.create("variableMeasured",       Optional, ONE,              [   (Schema.Text, OR)
                                                                                (Schema.PropertyValue, END)
                                                                            ],
                                                                            "A term to qualify the endpoint, or what is being computed (e.g. gene expression profiling or protein identification). The term can be free text or from, for example, a controlled vocabulary or an ontology.",
                                                                            "**THIS PROFILE**")
]

let profile = Profile.create(
    name = "ARCRun",
    required = requiredProfileProperties,
    recommended = recommendedProfileProperties,
    optional = optionalProfileProperties
)