module ARCWorkflow
open Domain

let requiredProfileProperties = [
    ProfileRow.create("@id",                    Required, ONE,              [   (Schema.Text, OR)
                                                                                (Schema.URL, END)
                                                                            ], 
                                                                            "Used to distinguish the resource being described in JSON-LD.", 
                                                                            "**THIS PROFILE**")
    ProfileRow.create("@type",                  Required, ONE,              [   (Schema.Dataset, END)], 
                                                                            "Schema.org/Bioschemas class(es) for the resource declared using JSON-LD syntax.", 
                                                                            "**THIS PROFILE**")
    ProfileRow.create("additionalType",         Required, ONE,              [   (Schema.Text, OR)
                                                                                (Schema.URL, END)
                                                                            ], 
                                                                            "MUST be 'ARC Workflow' or ontology term to identify it as an ARC Workflow", 
                                                                            "**THIS PROFILE**")
    ProfileRow.create("identifier",             Required, ONE,              [   (Schema.Text, OR)
                                                                                (Schema.URL, END)
                                                                            ], 
                                                                            "A mandatory unique identifier, either a temporary identifier supplied by users or one generated by a repository or other database. For example, it could be an identifier complying with the LSID specification", 
                                                                            "**THIS PROFILE**")
    ProfileRow.create("mainEntity",             Required, MANY,             [   (MultiTypes.WorkflowProtocol, END)],
                                                                            "The Main Workflow Protocol described by the ARC Workflow. MUST follow the [Workflow Protocol profile](#workflow-protocol).",
                                                                            "**THIS PROFILE**")
]
let recommendedProfileProperties = [
    ProfileRow.create("name",                   Recommended, ONE,           [   (Schema.Text, END)],
                                                                            "A concise phrase used to encapsulate the purpose and goal of the ARC Workflow.",
                                                                            "**THIS PROFILE**")
    ProfileRow.create("description",            Recommended, ONE,           [   (Schema.Text, END)],
                                                                            "A textual description of the ARC Workflow, with components such as objective or goals.",
                                                                            "**THIS PROFILE**")
    ProfileRow.create("hasPart",                Recommended, MANY,          [ 
                                                                                (Schema.MediaObject, OR)
                                                                                (MultiTypes.WorkflowProtocol, END)
                                                                            ],
                                                                            "All data files that are part of the ARC Workflow. In an ARC, this SHOULD include all contents of the respective `workflow folder` represented by the ARC Workflow object. Can also be used so signify sub-workflows that are part of this workflow's intended orchestration - if this is the case, MUST follow the [Workflow Protocol profile](#workflow-protocol).",
                                                                            "**THIS PROFILE**")
    ProfileRow.create("intendedUse",            Recommended, ONE,           [   (Schema.URL, OR)
                                                                                (Schema.DefinedTerm, END)
                                                                            ],
                                                                            "Term to classify the ARC Workflow. The term can be free text or from, for example, a controlled vocabulary or an ontology.",
                                                                            "**THIS PROFILE**")
]
let optionalProfileProperties = [
    ProfileRow.create("url",                    Recommended, ONE,           [   (Schema.URL, END)],
                                                                            "The filename or path of the metadata file describing the run. Optional, since in some contexts like an ARC the filename is implicit.",
                                                                            "**THIS PROFILE**")
    ProfileRow.create("version",                Recommended, ONE,           [   (Schema.Number, OR)
                                                                                (Schema.Text, END)
                                                                            ],
                                                                            "The filename or path of the metadata file describing the run. Optional, since in some contexts like an ARC the filename is implicit.",
                                                                            "**THIS PROFILE**")
]

let profile = Profile.create(
    name = "ARCWorkflow",
    required = requiredProfileProperties,
    recommended = recommendedProfileProperties,
    optional = optionalProfileProperties
)